### ISSUE TITLE
I can't log in with my Google Account.

### ISSUE THREAD

**Issue by CNLambda** [salomvary/soundcleod#102]
Hello,

as it says in the title, it doesn't work. I click on "Sign in with Google" and _nothing_ happens.
I guess it's a bug, but I don't know.
If I did something wrong, please point it out, but if it is a bug, _please_ fix it. I'll just use it as a player until then. (But searching for my account every time is just annoying)

I'll just thank you in advance for either fixing the bug or giving me a way around it.

- CodenameLambda

**Comment by salomvary** [comment]
G+ login not working has been known for a while, unfortunately not easy to fix:
https://github.com/salomvary/soundcleod/issues/53

Workaround: add an email/password while logged in to soundcloud.com using the website and then use that email/password pair with SoundCleod instead of the Google Account.
