### ISSUE TITLE
brew cask still has 0.18, is not updated

### ISSUE THREAD

**Issue by akaralar** [salomvary/soundcleod#106]
I'm using cask to install the app but when I run `brew cask install soundcleod` I get:

```
==> Verifying checksum for Cask soundcleod
==> Note: running "brew update" may fix sha256 checksum errors
Error: sha256 mismatch
Expected: 467761e18935787f2b1b89179236a31162521975b5104dfecb0869aec15403c9
Actual: 5f7bad26b2bb7b875787d63d4a0fd1cbfc4c9edf998a1e265fcc775a4b4b4eaf
File: /Users/akaralar/Library/Caches/Homebrew/soundcleod-0.18.dmg
```

Looking at the cask repo, the spec seems to be at 0.18

**Comment by salomvary** [comment]
The Homebrew install is maintained by the [Caskroom team](https://github.com/caskroom/homebrew-cask), please report problems there:
 https://github.com/caskroom/homebrew-cask#reporting-bugs

They probably link the installer from master (which changes with every version, hence the checksum error) instead of a tagged version.
