### ISSUE TITLE
Broken signatures

### ISSUE THREAD

**Issue by harrykiselev** [salomvary/soundcleod#156]
Márton, hello!

As I know 1.3.1 version is delayed due to broken signatures?
What signatures are you mean? Can we fix it here? :)

P.S. Thanks for Soundcleod, man! :)

**Comment by salomvary** [comment]
Yeah, sorry about that. Will try to fix it over the next few days.

For the record, the outline of the situation is:

- SoundCleod uses [Electron autoUpdater](https://electron.atom.io/docs/api/auto-updater/) for automatic updated which uses [Squirrel.Mac](https://github.com/Squirrel/Squirrel.Mac) on macOS behind the scenes
- Squirrel.Mac requires that the application is signed
- Apple wants [99 USD per year](https://developer.apple.com/support/purchase-activation/) for developer program which allows signing applications
- A free alternative is self-signing the application, however what I did not anticipate is what happens when the self signed certificate expires (which happened recently)
- In order to use a new self signed certificate, a new version has to be signed with the old one allowing to use the new signature
- To sign with an expired certificate, the computer's clock has to be set back
- In order to not require signing every future version of the app with the old signature, changes are needed on the update server too

**Comment by salomvary** [comment]
Fixed in 1.3.2.
