### ISSUE TITLE
Bug: Pause with Bluetooth headphones 

### ISSUE THREAD

**Issue by jugendhacker** [salomvary/soundcleod#159]
When I press the Pause button on my headphone it didn't pause! But the forward and backward buttons are working!

**Comment by salomvary** [comment]
I don't have a Bluetooth headphone but if someone has one and knows how to fix this, contributions are welcome:) Also related: https://github.com/salomvary/soundcleod/issues/104

**Comment by sammarcus** [comment]
This works for me: https://github.com/jguice/mac-bt-headset-fix

**Comment by jugendhacker** [comment]
But that's for Mac I have a Windows Computer

**Comment by jugendhacker** [comment]
@salomvary Can you say me where I can find the think with the media buttons in the source code?

**Comment by salomvary** [comment]
@jugendhacker you will want to call [`playPause`](https://github.com/salomvary/soundcleod/blob/master/app/soundcloud.js#L18) to start/stop playback. For instance the global media key shortcut calls it [from here](https://github.com/salomvary/soundcleod/blob/2e56950d9378044c76cbda3f2901a777745cc7d2/app/main.js#L119).

To be honest though if back/forward buttons already work out of the box I think that is because Electron (the framework SoundCleod is build with) turns them into media key events. If that is true I think it should handle play/pause button similarly. Maybe it's a bug/feature request to Electron itself?

But it might as well be the operating system turning the bluetooth buttons into media keys. Who knows...

Anyway, if you can find a simple fix for SoundCleod, pull request is welcome.

**Comment by jugendhacker** [comment]
@salomvary I think I found a solution for the problem but I need a bit help: I will test it and my question is how to run the program from the new sourcecode?

**Comment by salomvary** [comment]
@jugendhacker Check out the [development documentation](https://github.com/salomvary/soundcleod/blob/master/DEVELOPMENT.md).

**Comment by jugendhacker** [comment]
I found out how it works and now I made a pull request! #162

**Comment by jugendhacker** [comment]
@salomvary

**Comment by salomvary** [comment]
Landed in 1.3.3
