### ISSUE TITLE
Doesn't open properly

### ISSUE THREAD

**Issue by RobertasMurnikovas** [salomvary/soundcleod#199]
the app doesn't open on start, only can navigate to the last played track or profile/likes but neither does home/stream/library buttons works for me.
soundcleod 1.4.0
macos 10.15

**Comment by RobertasMurnikovas** [comment]
This is what it looks like when I open the app -> https://imgur.com/a/2iMDEAG

**Comment by salomvary** [comment]
Hey @RobertasMurnikovas, thanks for reporting this issue. Has it started happening since you upgraded macOS to Catalina (10.5)?

**Comment by RobertasMurnikovas** [comment]
hey, @salomvary , no it just started after random pc restart, i've tried to re-install the app but it didnt help, so I do know what could be the problem here

**Comment by salomvary** [comment]
@RobertasMurnikovas OK, that's interesting. Does https://soundcloud.com work if you open Chrome or Safari and try to log in?

**Comment by RobertasMurnikovas** [comment]
Yes, everything works using chrome/firefox/safari

**Comment by salomvary** [comment]
@RobertasMurnikovas Can you please get me a debugging screenshot from SoundCleod?

- Open the Terminal app in macOS
- Paste `/Applications/SoundCleod.app/Contents/MacOS/SoundCleod --developer-tools` and hit Enter
- Hit Command + Option + I
- Click Console on the newly opened Developer Tools Tab
- Take a screenshot using Command + Shift + 4 followed by Space and a click on the SoundCleod window and upload the screenshot here. It should look something like this:

<img width="1136" alt="Screenshot 2019-10-28 at 14 44 40" src="https://user-images.githubusercontent.com/193923/67683749-34ed0200-f992-11e9-8216-be721bb6dda0.png">

**Comment by RobertasMurnikovas** [comment]
@salomvary https://imgur.com/a/MXHaqbC

**Comment by salomvary** [comment]
@RobertasMurnikovas That's interesting. Getting `ERR_CONTENT_DECODING_FAILED` while trying to load `https://a-v2.sndcdn.com/assets/9-e78900f5-3.js` suggests that there is something odd with the networking on your macOS or between you and SoundCloud's servers. Are you using some custom firewall software on your computer? Is the clock of macOS set correctly?

**Comment by salomvary** [comment]
Side note:
@bruderstein it would be nice if SoundCloud showed a meaningful error message instead of blank content if a "major" script fails to load. I managed to reproduce a similar state by blocking a JS module from the Firefox Developer tools:

<img width="1200" alt="Screenshot 2019-10-28 at 16 45 50" src="https://user-images.githubusercontent.com/193923/67693954-dc723080-f9a2-11e9-898f-23d799366433.png">

**Comment by RobertasMurnikovas** [comment]
@salomvary , Yes, timezone is set correctly and i have no custom firewalls, just the regular macos firewall is turned on

**Comment by salomvary** [comment]
@RobertasMurnikovas In that case I am out of ideas. The problem might just go away or a soon-to-be-released next version might also fix it.

**Comment by bruderstein** [comment]
My bet is that this is a network blip or similar that meant that this file is now corrupt locally, and that due to the fairly strong caching requirements the "browser" never refreshes it. As @salomvary  said, this will probably fix itself when we update the file, which will likely be in the next 48 hours (but may not be, I've not looked what that file contains so it's possible it will be longer). If there's a way to clear the cache, that would also do it.

@salomvary i'll have a think & ask around if we can get an onerror handler on the script tag, that might be a way to handle errors like these.

**Comment by RobertasMurnikovas** [comment]
Okay guys, so I've fixed the problem. This time I cleared all the cached data and all related files and re-installed the app, now all works just the way it was. Previously I just tried to delete and install the app without going through all the caches and all that stuff. 
Either way I'm very thankful for your effort to help me with this silly issue!

**Comment by salomvary** [comment]
> I cleared all the cached data

Good move, I should have recommended that!
