### ISSUE TITLE
High CPU usage again?

### ISSUE THREAD

**Issue by orange-87** [salomvary/soundcleod#202]
@salomvary throttling on out of focus would definitely help a lot but ultimately, I don't think this is a problem you should have to solve.

Soundcloud support told me they have passed my report onto engineers.

I'll update this thread if/when I hear back!

_Originally posted by @JackCA in https://github.com/salomvary/soundcleod/issues/118#issuecomment-259260598_

**Comment by orange-87** [comment]
Hi I love your App! 

I have seen that the issue of high CPU usage is closed but still continues on me. I have version 1.4.0 on Mac OS X 10.11.6. When running it consumes 30 to 50% of the entire CPU even if the App is minimized. This causes significant computer slowdowns and micro cuts in the music. Does anyone still have this problem?

**Comment by salomvary** [comment]
@orange-87 Thanks for writing in! If you can provide data in the same fashion as I did on the previous issue (https://github.com/salomvary/soundcleod/issues/118#issuecomment-256308924), we can try comparing it with the old results and maybe come to a different conclusion, otherwise this is unlikely to be actionable.

**Comment by salomvary** [comment]
Closing due to lack of response.
