### ISSUE TITLE
FR: Lastfm scrobbler

### ISSUE THREAD

**Issue by farfromrefug** [salomvary/soundcleod#30]
I just discovered that app and i must say i really like it.
I miss a few features before switching from chrome to this.
And one of them is to be able to scrobble what i listen to to lastfm.
Currently i do that with [this](https://chrome.google.com/webstore/detail/lastfm-scrobbler/hhinaapppaileiechjoiifaancjggfjm)

Thanks for your amazing work!

**Comment by sammarcus** [comment]
Hi! Just wanted to double check, even with the electron rewrite this is still not on the agenda, correct?

**Comment by salomvary** [comment]
Definitely not. SoundCleod will never add/modify/remove features to soundcloud.com and this definitely falls into that category.

The only development I can imagine into this direction is exposing play/pause events from SoundCleod so that external applications can consume and implement whatever they want (including a Lastfm scrobbler). 

Created an issue here https://github.com/salomvary/soundcleod/issues/119 but I'm unlikely to implement this any time soon (contributions are always welcome).

**Comment by sammarcus** [comment]
That's what I had imagined. And thanks for #119, it seems like the most logical solve to this!
