### ISSUE TITLE
automate release process

### ISSUE THREAD

**Issue by salomvary** [salomvary/soundcleod#44]
create a Makefile to
- bump version
- build & sign .dmg
- update appcast
- update website

**Comment by vitorgalvao** [comment]
Two related notes:

+ There’s no release on github for `0.18.0` (it’s on the README, but not on the [releases page](https://github.com/salomvary/soundcleod/releases)).
+ There’s already an automated appcast, one that github makes, [here](https://github.com/salomvary/soundcleod/releases.atom) (simply add `.atom` to the releases page URL).

**Comment by salomvary** [comment]
Thanks, fixed, forgot to push the 0.18 tag.

The automated appcast isn't quite the same as the "manual" one. Compare:
https://github.com/salomvary/soundcleod/blob/master/appcast.xml
https://github.com/salomvary/soundcleod/releases.atom

`appcast.xml` is used for automatic updates and has to conform this specific schema (afaik).

**Comment by vitorgalvao** [comment]
Yes, they’re not the same, but they can be made pretty similar. You control the software, so if you release it (and actually append an app to download, instead of simply releasing the source) through github’s release page in a consistent manner, you can just as well grab that file and do what needs to be done to get the new version.

In the end, and appcast is just a text file, and you control it’s contents. It’s structure is, therefore, irrelevant because you can make your script just care about what you want consistently.

**Comment by salomvary** [comment]
Yep, however I did not implement automatic updates myself. SoundCleod uses Sparkle to do the heavy lifting. For good reasons there is no easy way to replace appcast with the github releases atom feed.

See also https://github.com/sparkle-project/Sparkle/issues/648

**Comment by salomvary** [comment]
As the Makefile does most of the releasing automatically, closing this.
